#!/bin/bash

# shard1
cmd="rs.initiate({_id:\"shard1\",members:[{_id:0,host:\"mongodockercompose_mongors1n1_1:27017\"},{_id:1,host:\"mongodockercompose_mongors1n2_1:27017\"},{_id:2,host:\"mongodockercompose_mongors1n3_1:27017\"}]})"
docker exec -it mongodockercompose_mongors1n1_1 bash -c "echo '${cmd}' | mongo admin"

# shard2
cmd="rs.initiate({_id:\"shard2\",members:[{_id:0,host:\"mongodockercompose_mongors2n1_1:27017\"},{_id:1,host:\"mongodockercompose_mongors2n2_1:27017\"},{_id:2,host:\"mongodockercompose_mongors2n3_1:27017\"}]})"
docker exec -it mongodockercompose_mongors2n1_1 bash -c "echo '${cmd}' | mongo admin"
